[package]
name = "prompto"
description = "Simple, functional, monadic command-line prompts."
version = "0.1.0"
authors = ["William Howell <wlm.howell@gmail.com>"]
license = "MIT"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
